---
sidebar: sidebar
permalink: codebox-automation.html
keywords: codebox, automation
summary: Codebox is an Infrastructure as Code (IaC) co-pilot that helps developers and DevOps generate the code needed to execute any operation supported by Workload Factory. Codebox is aligned with the Workload Factory operation modes (Basic, Read, Automate) and sets a clear path for execution readiness as well as an automation catalog for quick future reuse.
---

= Codebox automation
:icons: font
:imagesdir: ./media/

[.lead]
Codebox is an Infrastructure as Code (IaC) co-pilot that helps developers and DevOps generate the code needed to execute any operation supported by Workload Factory. Codebox is aligned with the Workload Factory operation modes (Basic, Read, Automate) and sets a clear path for execution readiness as well as an automation catalog for quick future reuse.

Code formats include Workload Factory REST APIs, AWS CLI, and AWS CloudFormation at this time.

Codebox deliver 2 key capabilities:  

* Codebox Viewer shows the IaC that is generated by a specific job flow operation, and is matched by a graphical wizard or conversational chat interface. While Codebox Viewer supports color coding and search for easy navigation and analysis, it does not allow editing - only copying or saving to the Automation Catalog. 

* Codebox Automation Catalog shows saved IaC jobs, allowing you to easily reference them for future use. Automation catalog jobs are saved as templates and shown in context of the resources that apply to them. 
