---
sidebar: sidebar
permalink: codebox-automation.html
keywords: codebox, automation
summary: Codebox is an Infrastructure as Code (IaC) co-pilot that helps developers and DevOps generate the code needed to execute any operation supported by Workload Factory. Codebox is aligned with the Workload Factory operation modes (Basic, Read, Automate) and sets a clear path for execution readiness as well as providing an automation catalog for quick future reuse.
---

= Codebox automation
:icons: font
:imagesdir: ./media/

[.lead]
Codebox is an Infrastructure as Code (IaC) co-pilot that helps developers and DevOps generate the code needed to execute any operation supported by Workload Factory. Codebox is aligned with the Workload Factory operation modes (Basic, Read, Automate) and sets a clear path for execution readiness as well as providing an automation catalog for quick future reuse.

Codebox provides two key capabilities:  

* _Codebox Viewer_ shows the IaC that is generated by a specific job flow operation by matching entries and selections from the graphical wizard or from the conversational chat interface. While Codebox Viewer supports color coding for easy navigation and analysis, it does not allow editing - only copying or saving code to the Automation Catalog. 

* _Codebox Automation Catalog_ shows all saved IaC jobs, allowing you to easily reference them for future use. Automation catalog jobs are saved as templates and shown in context of the resources that apply to them. 

== Supported code formats

The currently supported code formats include:

* Workload Factory REST APIs
* AWS CLI
* AWS CloudFormation

== How to use Codebox

You can see the data update in Codebox as you complete fields in the UI wizard.
