---
sidebar: sidebar
permalink: codebox-automation.html
keywords: codebox, automation
summary: Codebox is an Infrastructure as Code (IaC) co-pilot that helps developers and DevOps generate the code needed to execute any operation supported by Workload Factory. Codebox is aligned with the Workload Factory operation modes (Basic, Read, Automate) and it sets a clear path for execution readiness as well as providing an automation catalog for quick future reuse.
---

= Learn about codebox automation
:icons: font
:imagesdir: ./media/

[.lead]
Codebox is an Infrastructure as Code (IaC) co-pilot that helps developers and DevOps generate the code needed to execute any operation supported by Workload Factory. Codebox is aligned with the Workload Factory operation modes (Basic, Read, and Automate) and it sets a clear path for execution readiness as well as providing an automation catalog for quick future reuse.

== Codebox capabilities

Codebox provides two key IaC capabilities:  

* _Codebox Viewer_ shows the IaC that is generated by a specific job flow operation by matching entries and selections from the graphical wizard or from the conversational chat interface. While Codebox Viewer supports color coding for easy navigation and analysis, it does not allow editing--only copying or saving code to the Automation Catalog. 

* _Codebox Automation Catalog_ shows all saved IaC jobs, allowing you to easily reference them for future use. Automation catalog jobs are saved as templates and shown in context of the resources that apply to them. 

Additionally, when setting up Workload Factory credentials, Codebox dynamically displays the AWS permissions that are needed to create IAM policies. The permissions are provided for each Workload Factory capability that you plan to use (databases, AI, FSx for ONTAP, and so on), and they are customized based on whether the users of the policy will get read-only permissions or full operate permissions. You just copy the permissions from Codebox and then paste them in the AWS Management Console so that Workload Factory has the correct permissions to manage your workloads.

== Supported code formats

The supported code formats include:

* Workload Factory REST APIs
* AWS CLI
* AWS CloudFormation

link:use-codebox.html[Learn how to use Codebox].
