---
sidebar: sidebar
permalink: configure-notifications.html
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts
summary: You can configure NetApp Workload Factory to send notifications to a person or another application when certain types of events happen. 
---

= Configure NetApp Workload Factory notifications 
:icons: font
:imagesdir: ./media/

[.lead]
You can configure the NetApp Workload Factory notification service to send notifications as alerts in the NetApp Console or to an Amazon SNS topic. Notifications sent as alerts appear in NetApp Console when you have a Console agent or link deployed. When Workload Factory publishes notifications to an Amazon SNS topic, subscribers to the topic (such as people or other applications) receive the notifications at the endpoints configured for the topic (such as email or SMS messages).

== Notification types and messages
Workload Factory sends notifications for the following events:

[cols=6*,options="header,autowidth"]
|===

| Event
| Description
| Notification type
| Severity
| Workload
| Resource type

| Some database instances in your account are not well-architected
| All Microsoft SQL Server instances in your account have been analyzed for well-architected issues. The description for this event gives the number of well-architected instances and unoptimized instances. Review well-architected status findings and recommendations in the Databases inventory from the Workload Factory console.
| Well-architected
| Recommendation
| Databases
| Microsoft SQL Server instance

| Microsoft SQL Server/PostgreSQL server deployment succeeded
| The deployment of the Microsoft SQL Server or PostgreSQL host succeeded. For more information, go to job monitoring.
| Deployment
| Success
| Databases
| FSx for ONTAP, DB host

| Microsoft SQL Server/PostgreSQL server deployment failed
| The deployment of the Microsoft SQL Server or PostgreSQL host failed. For more information, go to job monitoring.
| Deployment
| Error
| Databases
| FSx for ONTAP, DB host

| Failed replication relationship creation
| A SnapMirror replication relationship creation has failed. For more information, go to Tracker.
| Replication
| Critical
| General storage
| FSx for ONTAP

| FSx for ONTAP creation failure
| An FSx for ONTAP file system creation process has failed. For more information, go to Tracker.
| FSx for ONTAP file system action
| Critical
| General storage
| FSx for ONTAP

| Automatic SSD capacity or inodes increase success
| During a recent automatic capacity management update, the FSx for ONTAP file system either increased SSD capacity or volume inodes successfully. For more information, go to Tracker.
| Capacity management
| Success
| General storage
| FSx for ONTAP file 

| Automatic SSD capacity or inodes increase failure
| During a recent automatic capacity management update, the FSx for ONTAP file system failed to increase SSD capacity or volume inodes. For more information, go to Tracker.
| Capacity management
| Critical
| General storage
| FSx for ONTAP file systems

| FSx for ONTAP issue detected
| All FSx for ONTAP file systems have been analyzed for well-architected issues. The scan detected one or more issues. For more information, review the well-architected analysis from the Storage dashboard in the Workload Factory console.
| Well-architected analysis
| Recommendation
| General storage
| FSx for ONTAP file systems

|===

== Configure Workload Factory notifications
Configure Workload Factory notifications using the NetApp Console or the Workload Factory console. If you use the NetApp Console, you can configure Workload Factory to send notifications as alerts in the NetApp Console or to an Amazon SNS topic. You can configure notifications from the *Notifications settings* in the NetApp Console.

.Before you begin

* You need to configure Amazon SNS and create Amazon SNS topics using either the Amazon SNS console or the AWS CLI.
* Note that Workload Factory supports the *Standard* topic type. This type of topic does not ensure that notifications are sent to subscribers in the order in which they were received, so consider this if you have critical or emergency notifications.

[role="tabbed-block"]
====

.Configure notifications from NetApp Console
--
.Steps

. Log in to the link:https://console.netapp.com[NetApp Console^].
. From the NetApp Console menu, select *Workloads*, *Administration*, and then *Notifications setup*.
. On the Notifications setup page, do the following:
.. Optional: Select *Enable NetApp Console notifications* to configure Workload Factory to send notifications in the NetApp Console.
.. Select *Enable SNS notifications*.
.. Follow the instructions to configure Amazon SNS from the Amazon SNS console.
+
After you create the topic, copy the topic ARN and enter it in the *SNS topic ARN* field on the *Notifications setup* page.
. After you verify the configuration by sending a test notification, select *Apply*.

.Result
Workload Factory is configured to send notifications to the Amazon SNS topic that you specified.
--
.Configure notifications from Workload Factory console
--
.Steps

. Log in to the link:https://console.workloads.netapp.com[Workload Factory console^].
. From the Workload Factory console menu, select *Workloads*, *Administration*, and then *Notifications setup*.
. Select *Enable SNS notifications*.
. Follow the instructions to configure Amazon SNS from the Amazon SNS console.
. After you verify the configuration by sending a test notification, select *Apply*.

.Result
Workload Factory is configured to send notifications to the Amazon SNS topic that you specified.
--
====

== Subscribe to the Amazon SNS topic
After you configure Workload Factory to send notifications to a topic, follow the https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html[instructions] in the Amazon SNS documentation to subscribe to the topic so that you can receive notifications from Workload Factory.

== Filter notifications
You can reduce unnecessary notification traffic and target specific notification types for specific users by applying filters to the notifications. You can do this using an Amazon SNS policy for SNS notifications, and using the notifications settings in the NetApp Console.

=== Filter Amazon SNS notifications
When you subscribe to an Amazon SNS topic, you receive all notifications published to that topic by default. If you want to receive only specific notifications from the topic, you can use a filter policy to control which notifications you receive. Filter policies cause Amazon SNS to deliver only the notifications that match the filter policy to the subscriber.

You can filter Amazon SNS notifications by the following criteria:

[cols=3*,options="header,autowidth"]
|===

| Description
| Filter policy field name
| Possible values

| Resource type
| `resourceType`
a|

* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`
//* `Test resource type`


| Workload
| `workload`
| `WLMDB`

//* `FSX`
//* `Test workload`
//* `WLMAI`
//* `WLMVMC`

| Priority
| `priority`
a|

* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`

| Notification type
| `notificationType`
a|

* `Deployment`
//* `Test notification type`
* `Well-architected`

|===

.Steps

. In the Amazon SNS console, edit the subscription details for the SNS topic.
. In the *Subscription filter policy* area, select to filter by *Message attributes*.
. Enable the *Subscription filter policy* option.
. Enter a JSON filter policy in the *JSON editor* box.
+
For example, the following JSON filter policy accepts notifications from the Microsoft SQL Server resource that are related to the WLMDB workload, have a priority of Success or Error, and provide details on Well-architected status:
+
[source,json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. Select *Save changes*.

For other examples of filter policies, refer to https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html[Amazon SNS example filter policies^].

For further information about creating filter policies, refer to the https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html[Amazon SNS documentation^].


=== Filter notifications in the NetApp Console
You can use the NetApp Console notifications settings to filter notifications that you receive in the Console by severity level, such as Critical, Info, or Warning.

For more information about filtering notifications in the Console, refer to the https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications[NetApp Console documentation^].

