---
sidebar: sidebar
permalink: configure-notifications.html
keywords: amazon, sns, notification, topic, notifications
summary: You can configure workload factory to send notifications to a person or another application when certain types of events happen. 
---

= Configure notifications
:icons: font
:imagesdir: ./media/

[.lead]
You can configure workload factory to send notifications to a person or another application when certain types of events happen. Workload factory publishes notifications to Amazon SNS topics, and subscribers to the topic receive the notifications.

.About this task

* You need to configure Amazon SNS through either the Amazon SNS console, or using the AWS CLI.
* The cost for sending notifications is per message, and determined by Amazon.
* Workload factory supports the *Standard* topic type. This type of topic does not ensure that notifications are sent to subscribers in the order in which they were received.
* You can configure notifications from the BlueXP console or from the workload factory console.

[role="tabbed-block"]
====

.Configure notifications from the BlueXP console
--
.Steps

. Log in to the link:https://console.bluexp.netapp.com[BlueXP console^].
. Select *Workloads* from the left navigation. 
. Select *Home* to view all workloads or select one workload like *Storage* or *Databases*. 
. From the workload factory menu bar, select the configuration menu.
. In the menu, select *Workload Factory notification setup*.
. Optional: Select *Enable BlueXP notifications* to configure workload factory to send notifications to BlueXP.
. Select *Enable SNS notifications*.
. Follow the instructions to configure Amazon SNS from the Amazon SNS console.
. After you verify the configuration by sending a test notification, select *Apply*.

.Result
Workload factory is configured to send notifications to the Amazon SNS topic that you specified.
.  
--
.Configure notifications from workload factory console
--
.Steps

. Log in to the link:https://console.workloads.netapp.com[workload factory console^].
. Open the account menu from the top navigation bar.
. In the menu, select *Notification setup*.
. Select *Enable SNS notifications*.
. Follow the instructions to configure Amazon SNS from the Amazon SNS console.
. After you verify the configuration by sending a test notification, select *Apply*.

.Result
Workload factory is configured to send notifications to the Amazon SNS topic that you specified.
--
====