---
sidebar: sidebar
permalink: configure-notifications.html
keywords: amazon, sns, notification, topic, notifications
summary: You can configure workload factory to send notifications to a person or another application when certain types of events happen. 
---

= Configure notifications
:icons: font
:imagesdir: ./media/

[.lead]
You can configure workload factory to send notifications to an Amazon SNS topic when certain types of events happen. After workload factory publishes a notification to an Amazon SNS topic, subscribers (such as an individual or another application) to the topic receive the notifications.

== Configure workload factory notifications

.About this task

* You need to configure Amazon SNS and create Amazon SNS topics through either the Amazon SNS console, or using the AWS CLI.
* Workload factory supports the *Standard* topic type. This type of topic does not ensure that notifications are sent to subscribers in the order in which they were received.
* You can configure workload factory notifications using the BlueXP console or the workload factory console.

[role="tabbed-block"]
====

.Configure notifications from the BlueXP console
--
.Steps

. Log in to the link:https://console.bluexp.netapp.com[BlueXP console^].
. Select *Workloads* from the left navigation. 
. Select *Home* to view all workloads or select one workload like *Storage* or *Databases*. 
. From the workload factory menu bar, select the configuration menu.
. In the menu, select *Workload Factory notification setup*.
. Optional: Select *Enable BlueXP notifications* to configure workload factory to send notifications to BlueXP.
. Select *Enable SNS notifications*.
. Follow the instructions to configure Amazon SNS from the Amazon SNS console.
+
After you create the topic, copy the topic ARN and enter it in the *SNS topic ARN* field in the *Notification setup* dialog. 
. After you verify the configuration by sending a test notification, select *Apply*.

.Result
Workload factory is configured to send notifications to the Amazon SNS topic that you specified.
--
.Configure notifications from workload factory console
--
.Steps

. Log in to the link:https://console.workloads.netapp.com[workload factory console^].
. Open the account menu from the top navigation bar.
. In the menu, select *Notification setup*.
. Select *Enable SNS notifications*.
. Follow the instructions to configure Amazon SNS from the Amazon SNS console.
. After you verify the configuration by sending a test notification, select *Apply*.

.Result
Workload factory is configured to send notifications to the Amazon SNS topic that you specified.
--
====

== Subscribe to the Amazon SNS topic
After you configure workload factory to send notifications to a topic, follow the https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html[instructions] in the Amazon SNS documentation to subscribe to the topic so that you can receive notifications from workload factory.