---
sidebar: sidebar
permalink: connectivity-links.html
keywords: links, accounts, lambda
summary: A Workload Factory link creates a trust relationship and connectivity between Workload Factory and an AWS account. You don't need a link to get started with Workload Factory, but in some cases you'll need to create a link to unlock all Workload Factory features and workload capabilities.
---

= Connectivity links
:icons: font
:imagesdir: ./media/

[.lead]
A Workload Factory link creates a trust relationship and connectivity between Workload Factory and an AWS account. You don't need a link to get started with Workload Factory, but in some cases you'll need to create a link to unlock all Workload Factory features and workload capabilities. 

Links leverage AWS Lambda. Lambda executes code in response to events and automatically manages the computing resources required by that code. The links that you create are part of your NetApp account and they are associated with an AWS account.

After you have created a link you can associate it with your FSx for ONTAP file systems. Each file system or resource can be associated only to one link, but a link can be associated with many file systems or resources. If necessary, you can disassociate a resource from a link.

You can create a link from your account or you can create one when defining your FSx for ONTAP system. link:manage-links.html[See how to create links] for details.


== What you can do without a link

Most features in Workload Factory do not require a link. You can perform the following tasks without needing a link:

* this
* and that

== When a link is required

Workload Factory requires a link to perform some tasks. These tasks include:

* this
* and that
