---
sidebar: sidebar
permalink: connectivity-links.html
keywords: links, accounts, lambda
summary: A Workload Factory link creates a trust relationship and connectivity between a Workload Factory account and one or more FSx for ONTAP file systems. This enables you to monitor and manage certain file system features directly from the ONTAP REST APIs that are not available through the Amazon FSx for ONTAP APIs.
---

= Connectivity links
:icons: font
:imagesdir: ./media/

[.lead]
A Workload Factory link creates a trust relationship and connectivity between a Workload Factory account and one or more FSx for ONTAP file systems. This enables you to monitor and manage certain file system features directly from the ONTAP REST APIs that are not available through the Amazon FSx for ONTAP APIs.

You don't need a link to get started with Workload Factory, but in some cases you'll need to create a link to unlock all Workload Factory features and workload capabilities. 

== How do links work

Links leverage AWS Lambda. Lambda executes code in response to events and automatically manages the computing resources required by that code. The links that you create are part of your NetApp account and they are associated with an AWS account.

After you have created a link you can associate it with your FSx for ONTAP file systems. Each file system can be associated only to one link, but a link can be associated with many file systems. If necessary, you can disassociate a file system from using a link.

You create links from the FSx for ONTAP file system pages in Workload Factory. link:manage-links.html[See how to create links] for details.

== Costs

There is a minimal charge to your AWS account for each transaction that Lambda performs. Since Lambda acts as a proxy between the two systems, there is a charge when Lambda sends a request to the ONTAP REST APIs on a file system, and when it sends the response back to Workload Factory.

https://aws.amazon.com/lambda/pricing/[Learn more about the costs related to using AWS Lambda.]

== What you can do without a link

Most features in Workload Factory do not require a link. You can perform the following tasks without needing a link:

* Create FSx for ONTAP file systems.
* this
* and that

== When a link is required

Workload Factory requires a link to display some information and to perform some tasks. If you attempt to perform an operation that requires a link and you haven't associated a link with the FSx for ONTAP system, you will see a message that the operation requires a link. You can associate a link at that time so you can perform the operation.

The features that you can't access without having a link includes:

* Display the version of ONTAP that is installed on an FSx for ONTAP file system.
* Manage iSCSI volumes on the system.
* Enable and disable the Autogrow feature for volumes.
* Manage snapshot policies.
* Configure replication relationships and replicate volumes between file systems.
* Configure backup relationships and backup volume data to cloud storage.
* Clone volumes within a file system.
* Display additional metrics directly from ONTAP - default metrics are collected by Amazon CloudWatch.
* more
