---
sidebar: sidebar
permalink: console-experiences.html
keywords: console, consoles, access, saas, Workload Factory, bluexp, NetApp Workload Factory, NetApp Console
summary: "NetApp Workload Factory is accessible via two web-based consoles." 
---

= Console experiences
:icons: font
:imagesdir: ./media/

[.lead]
NetApp Workload Factory is accessible via two web-based consoles. Learn how to access Workload Factory using the Workload Factory console and the NetApp Console. 

* *NetApp Console*: Offers a hybrid experience where you can manage your FSx for ONTAP file systems and workloads running on Amazon FSx for NetApp ONTAP in the same place. 
* *Workload Factory console*: Offers a dedicated Workload Factory experience focused on workloads running on Amazon FSx for NetApp ONTAP. 

== Access Workload Factory in the NetApp Console

You can access Workload Factory from the NetApp Console. In addition to using Workload Factory for AWS storage and workload capabilities, you can also access other data services like NetApp Copy and Sync and more.

.Steps
. Log in to the link:https://console.netapp.com[NetApp Console^].
. From the NetApp Console menu, select *Workloads* and then *Overview*. 

== Access Workload Factory in the Workload Factory console

You can access Workload Factory from the Workload Factory console. 

.Step

. Log in to the link:https://console.workloads.netapp.com[Workload Factory console^].