---
sidebar: sidebar
permalink: credentials-overview.html
keywords: aws, aws accounts, keys, multiple accounts, permissions, aws permissions, policy, policies, credentials
summary: Learn how Workload Factory uses AWS credentials to perform actions on your behalf. Understanding these details can be helpful as you manage the credentials for one or more AWS accounts in Workload Factory. For example, you might want to learn about when to add additional AWS credentials or permissions to Workload Factory.
---

= Learn about credentials and permissions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn how Workload Factory uses AWS credentials to perform actions on your behalf. Understanding these details can be helpful as you manage the credentials for one or more AWS accounts in Workload Factory. For example, you might want to learn about when to add additional AWS credentials or permissions to Workload Factory.

We have designed an AWS assume role credentials registration flow that: 

* Supports a more aligned AWS account permissions by allowing you to specify the workload capabilities you want to use and providing IAM policy requirements according to those selections.  
* Allowing you to adjust the granted AWS account permissions as you opt-in or opt-out of specific workload capabilities. 
* Simplifies manual IAM policy creation by providing tailored policy JSON files that can be applied in the AWS console.
* Further simplify the credentials registration process by offering users with an automated option for required IAM policy and role creation using AWS CloudFormation stacks.
* Align better with FSx for ONTAP users who strongly prefer to have their credentials stored within the boundaries of the AWS cloud ecosystem by allowing storage of the FSx for ONTAP services credentials in an AWS-based secret management backend.

== Initial AWS credentials

When you use your first Workload Factory capability, you'll need to create the credentials using the permissions required for the capability. You'll create the credentials in Workload Factory, but you'll need to access the AWS Management Console to create the IAM role and policy. These credentials will be available within your account when using any capability in Workload Factory. 

== Additional AWS credentials

Adding new AWS credentials to Workload Factory provides additional permissions needed to use additional capabilities, such as FSx for ONTAP file systems, deploy databases on FSx for ONTAP, migrate VMware workloads, and more.

link:manage-credentials.html[Learn how to add AWS credentials to Workload Factory^]
