---
sidebar: sidebar
permalink: manage-service-accounts.html
keywords: service account, service accounts, manage account, create service account, delete service account, workload factory service account
summary: You can manage your account to fit your needs by creating service accounts for automation purposes.
---

= Manage service accounts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Create service accounts to act as machine users that automate infrastructure operations.

Service accounts make it easier to manage automation because you don't need to build automation scripts based on a real person's user account who can leave the company at any time. Service accounts also help remove required dependencies, management overhead, and risks in information security breaches. 

Several service accounts can be associated with a BlueXP workload factory account. You might create one service to deploy database servers and another service account to build your ... (Builders use case).

== How service accounts work

Service accounts are made possible by multi-tenancy functionality in BlueXP. Permissions are given to a service account using the account admin role. 

Tokens are granted ...

Note that a refresh token is not required for API operations when using a service account. link:https://docs.netapp.com/us-en/bluexp-automation/platform/grant_types.html#refresh-token[Learn about refresh tokens^]

== Create a service account
When you create the service account, BlueXP workload factory enables you to copy or download a client ID and client secret for the service account. This key pair is used for authentication with BlueXP workload factory.

.Steps
. In the Workload Factory console, select the *Account* icon, and select *Service accounts*.

. On the *Service accounts* page, click *Create service account*. 

. In the Create service account dialog, enter a name for the service account in the *Service account name* field. 

. The *role* is preselected as *account admin*. 

. Select *Continue*. 

. Copy or download the client ID and client secret.
+
The client secret is visible only once and is not stored anywhere by workload factory. Copy or download the secret and store it safely.

. Optionally, you can get an access token for Auth0 management API by executing a client credentials exchange. 

. Select *Close*. 

The new service account is created and listed on the Service accounts page. 

== Delete a service account
Delete a service account if you no longer need to use it.

.Steps

. In the Workload Factory console, select the *Account* icon, and select *Service accounts*.

. On the *Service accounts* page, click the three-dot menu and then click *Delete*. 

. In the Delete service account dialog, enter *delete* in the text box. 

. Select *Delete* to confirm deletion. 

The service account is deleted. 
