---
sidebar: sidebar
permalink: manage-service-accounts.html
keywords: service account, service accounts, manage account, create service account, delete service account, workload factory service account
summary: You can manage your account to fit your needs by creating service accounts for automation purposes.
---

= Manage service accounts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Create service accounts to act as machine users that automate infrastructure operations. You can revoke or change access to service accounts at any time.

.About this task

Service accounts are a multi-tenancy functionality provided by BlueXP. Account admins create, control access, and delete service accounts. You can manage service accounts in the BlueXP console or in the BlueXP workload factory console. 

Unlike managing service accounts in BlueXP where you can recreate a client secret, workload factory supports creation and deletion of service accounts. If you want to recreate a client secret for a specific service account in the BlueXP workload factory console, you'll need to <<Delete a service account,delete the service account>>, and then <<Create a service account,create a new one>>. 

Client IDs and secrets are fixed until the account admin decides to change them. There is no password policy associated with service accounts. To use a service account, you'll need the client ID and secret to generate the access token or you won't gain access. Keep in mind that access tokens are short-lived and can only be used for several hours. 

NOTE: Service accounts are currently available for the Builders workload.

.Before you begin
* Decide if you want to create a service account in the BlueXP console or in the Workload Factory console. There are slight differences. The following instructions describe how to manage service accounts in the BlueXP workload factory console. 
+
To manage service accounts in BlueXP, refer to link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-netapp-accounts.html#create-and-manage-service-accounts[BlueXP setup and admin documentation on managing service accounts^]. 

== Create a service account
When you create the service account, BlueXP workload factory enables you to copy or download a client ID and client secret for the service account. This key pair is used for authentication with BlueXP workload factory. the curl example shows how can you take the client id and secret and use an API to generate the access token which are time-limited. The token provides several hours of access to access the WF APIs.

.Steps
. In the Workload Factory console, select the *Account* icon, and select *Service accounts*.

. On the *Service accounts* page, click *Create service account*. 

. In the Create service account dialog, enter a name for the service account in the *Service account name* field. 

. The *role* is preselected as *account admin*. 

. Select *Continue*. 

. Copy or download the client ID and client secret.
+
The client secret is visible only once and is not stored anywhere by workload factory. Copy or download the secret and store it safely.

. Optionally, you can get an access token for Auth0 management API by executing a client credentials exchange. The curl example shows how can you take the client ID and secret and use an API to generate the access token which are time-limited. The token provides several hours of access to access the BlueXP workload factory APIs.

. Select *Close*. 

The new service account is created and listed on the Service accounts page. 

== Delete a service account
Delete a service account if you no longer need to use it.

.Steps

. In the Workload Factory console, select the *Account* icon, and select *Service accounts*.

. On the *Service accounts* page, click the three-dot menu and then click *Delete*. 

. In the Delete service account dialog, enter *delete* in the text box. 

. Select *Delete* to confirm deletion. 

The service account is deleted. 
