---
sidebar: sidebar
permalink: operational-modes.html
keywords: modes, zero-trust, full-trust
summary: Workload Factory provides three operational modes that you can assign for users in your AWS accounts to carefully control access between Workload Factory and your cloud estate based on your IT policies.
---

= Operational modes
:icons: font
:imagesdir: ./media/

[.lead]
Workload Factory provides three operational modes that you can assign for users in your AWS accounts to carefully control access between Workload Factory and your cloud estate based on your IT policies.

A logical organization of the functionality and capabilities delivered by Workload Factory, as correlated to the trust level assigned by the customer. Operational Modes is not a feature per-se, and accordingly does not have a graphical UI representation. The main objective in Operational Modes is to clearly communicate to the user, what Workload Factory can or cannot do.   

*Basic mode*:: Represents zero-trust relationship and is designed for early exploration of Workload Factory and usage of the various wizards to create the needed Infrastructure as Code (IaC). This code can be copied and used manually by the user along with their relevant AWS credentials.  

*Read mode*:: Enhances the experience of Basic mode by assisting the user in detecting various resources and tools, and consequently, helping to complete relevant wizards. 

*Automate mode*:: Represents a full trust relationship and is designed to execute and automate on behalf of the user along with the assigned credentials that have the needed and validated permissions for execution. 

This table lists the features available for each of the modes.

[options="header",cols="16h,26,26,26"]
|===
| Modes
| Automation
| AWS resource discovery and auto-complete
| Progress monitoring

| Basic
| DYI with skeleton IaC template
| No
| No

| Read
| DYI with populated IaC template
| Yes
| Yes

| Automate
| Yes
| Yes
| Yes

|===

This table lists the requirements for using these modes.

[options="header",cols="16h,35,35"]
|===
| Modes
| AWS Account Credentials
| Connectivity Links

| Basic
| Not required
| Not required

| Read
| Read-only
| Not required

| Automate
| Applicable cloud and/or on-prem ONTAP credentials
| Yes

|===

== d


