---
sidebar: sidebar
permalink: permissions-reference.html
keywords: permissions, actions
summary: To use Workload Factory features and services, you'll need to provide permissions so that Workload Factory can perform operations in your cloud environment. 
---

= Permissions for Workload Factory
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To use Workload Factory features and services, you'll need to provide permissions so that Workload Factory can perform operations in your cloud environment. 

== Why use permissions
When you provide read or automate mode permissions, Workload Factory attaches a policy to the instance with permissions to manage resources and processes within that AWS account. This allows Workload Factory to execute various operations starting from discovery of your storage environments to deploying AWS resources such as file systems in storage management or knowledge bases for GenAI workloads. 

For database workloads for example, when Workload Factory is granted with the required permissions, it scans all EC2 instances in a given account and region, and filters all Windows-based machines. If SSM is installed and running on the host and System Manager networking is configured properly, Workload Factory can access the Windows machine and verify whether SQL Server software is installed or not.

== IAM policies
The IAM policies available below provide the permissions that Workload Factory needs to manage resources and processes within your public cloud environment based on the operational mode you operate in.

Select your operational mode to view the required policies:

[role="tabbed-block"]
=====
.Read mode
--
[source,json]
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "CommonGroup",
      "Effect": "Allow",
      "Action": [
        "cloudwatch:GetMetricStatistics",
        "sns:ListTopics",
        "ec2:DescribeInstances",
        "ec2:DescribeVpcs",
        "ec2:DescribeSubnets",
        "ec2:DescribeSecurityGroups",
        "ec2:DescribeImages",
        "ec2:DescribeRegions",
        "ec2:DescribeRouteTables",
        "ec2:DescribeKeyPairs",
        "ec2:DescribeNetworkInterfaces",
        "ec2:DescribeInstanceTypes",
        "ec2:DescribeVpcEndpoints",
        "ec2:DescribeInstanceTypeOfferings",
        "ec2:DescribeSnapshots",
        "ec2:DescribeVolumes",
        "kms:ListAliases",
        "kms:ListKeys",
        "kms:DescribeKey",
        "cloudformation:ListStacks",
        "ds:DescribeDirectories",
        "fsx:DescribeVolumes",
        "fsx:DescribeBackups",
        "fsx:DescribeStorageVirtualMachines",
        "fsx:DescribeFileSystems",
        "servicequotas:ListServiceQuotas",
        "ssm:GetParametersByPath",
        "ssm:GetCommandInvocation",
        "ssm:SendCommand",
        "ssm:GetConnectionStatus",
        "fsx:ListTagsForResource"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Sid": "SSMParameterStore",
      "Effect": "Allow",
      "Action": [
        "ssm:GetParameter",
        "ssm:GetParameters",
        "ssm:PutParameter",
        "ssm:DeleteParameters"
      ],
      "Resource": "arn:aws:ssm:*:*:parameter/netapp/wlmdb/*"
    }
  ]
}

--
.Automate mode
--
[source,json]
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "EC2Group",
      "Effect": "Allow",
      "Action": [
        "ec2:AllocateAddress",
        "ec2:AllocateHosts",
        "ec2:AssignPrivateIpAddresses",
        "ec2:AssociateAddress",
        "ec2:AssociateRouteTable",
        "ec2:AssociateSubnetCidrBlock",
        "ec2:AssociateVpcCidrBlock",
        "ec2:AttachInternetGateway",
        "ec2:AttachNetworkInterface",
        "ec2:AttachVolume",
        "ec2:AuthorizeSecurityGroupEgress",
        "ec2:AuthorizeSecurityGroupIngress",
        "ec2:CreateVolume",
        "ec2:DeleteNetworkInterface",
        "ec2:DeleteSecurityGroup",
        "ec2:DeleteTags",
        "ec2:DeleteVolume",
        "ec2:DetachNetworkInterface",
        "ec2:DetachVolume",
        "ec2:DisassociateAddress",
        "ec2:DisassociateIamInstanceProfile",
        "ec2:DisassociateRouteTable",
        "ec2:DisassociateSubnetCidrBlock",
        "ec2:DisassociateVpcCidrBlock",
        "ec2:ModifyInstanceAttribute",
        "ec2:ModifyInstancePlacement",
        "ec2:ModifyNetworkInterfaceAttribute",
        "ec2:ModifySubnetAttribute",
        "ec2:ModifyVolume",
        "ec2:ModifyVolumeAttribute",
        "ec2:ReleaseAddress",
        "ec2:ReplaceRoute",
        "ec2:ReplaceRouteTableAssociation",
        "ec2:RevokeSecurityGroupEgress",
        "ec2:RevokeSecurityGroupIngress",
        "ec2:StartInstances",
        "ec2:StopInstances"
      ],
      "Resource": "*",
      "Condition": {
        "StringLike": {
          "ec2:ResourceTag/aws:cloudformation:stack-name": "WLMDB*"
        }
      }
    },
    {
      "Sid": "FSxNGroup",
      "Effect": "Allow",
      "Action": [
        "fsx:TagResource"
      ],
      "Resource": "*",
      "Condition": {
        "StringLike": {
          "aws:ResourceTag/aws:cloudformation:stack-name": "WLMDB*"
        }
      }
    },
    {
      "Sid": "CommonGroup",
      "Effect": "Allow",
      "Action": [
        "cloudformation:CreateStack",
        "cloudformation:DescribeStackEvents",
        "cloudformation:DescribeStacks",
        "cloudformation:ListStacks",
        "cloudformation:ValidateTemplate",
        "cloudwatch:GetMetricStatistics",
        "ds:DescribeDirectories",
        "ec2:CreateLaunchTemplate",
        "ec2:CreateLaunchTemplateVersion",
        "ec2:CreateNetworkInterface",
        "ec2:CreateSecurityGroup",
        "ec2:CreateTags",
        "ec2:CreateVpcEndpoint",
        "ec2:Describe*",
        "ec2:Get*",
        "ec2:RunInstances",
        "ec2:ModifyVpcAttribute",
        "ec2messages:*",
        "fsx:CreateFileSystem",
        "fsx:CreateStorageVirtualMachine",
        "fsx:CreateVolume",
        "fsx:Describe*",
        "fsx:List*",
        "kms:CreateGrant",
        "kms:Describe*",
        "kms:List*",
        "kms:GenerateDataKey",
        "kms:Decrypt",
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:DescribeLog*",
        "logs:GetLog*",
        "logs:ListLogDeliveries",
        "logs:PutLogEvents",
        "logs:TagResource",
        "servicequotas:ListServiceQuotas",
        "sns:ListTopics",
        "sns:Publish",
        "ssm:Describe*",
        "ssm:Get*",
        "ssm:List*",
        "ssm:PutComplianceItems",
        "ssm:PutConfigurePackageResult",
        "ssm:PutInventory",
        "ssm:SendCommand",
        "ssm:UpdateAssociationStatus",
        "ssm:UpdateInstanceAssociationStatus",
        "ssm:UpdateInstanceInformation",
        "ssmmessages:*"
      ],
      "Resource": "*"
    },
    {
      "Sid": "ArnGroup",
      "Effect": "Allow",
      "Action": [
        "cloudformation:SignalResource"
      ],
      "Resource": [
        "arn:aws:cloudformation:*:*:stack/WLMDB*",
        "arn:aws:logs:*:*:log-group:WLMDB*"
      ]
    },
    {
      "Sid": "IAMGroup",
      "Effect": "Allow",
      "Action": [
        "iam:AddRoleToInstanceProfile",
        "iam:CreateInstanceProfile",
        "iam:CreateRole",
        "iam:DeleteInstanceProfile",
        "iam:GetPolicy",
        "iam:GetPolicyVersion",
        "iam:GetRole",
        "iam:GetRolePolicy",
        "iam:GetUser",
        "iam:PutRolePolicy",
        "iam:RemoveRoleFromInstanceProfile",
        "iam:SimulatePrincipalPolicy"
      ],
      "Resource": "*"
    },
    {
      "Sid": "IAMGroup1",
      "Effect": "Allow",
      "Action": "iam:CreateServiceLinkedRole",
      "Resource": "*",
      "Condition": {
        "StringLike": {
          "iam:AWSServiceName": "ec2.amazonaws.com"
        }
      }
    },
    {
      "Sid": "IAMGroup2",
      "Effect": "Allow",
      "Action": "iam:PassRole",
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "iam:PassedToService": "ec2.amazonaws.com"
        }
      }
    },
    {
      "Sid": "SSMParameterStore",
      "Effect": "Allow",
      "Action": [
        "ssm:GetParameter",
        "ssm:GetParameters",
        "ssm:PutParameter",
        "ssm:DeleteParameters"
      ],
      "Resource": "arn:aws:ssm:*:*:parameter/netapp/wlmdb/*"
    }
  ]
}
--
=====
// end tabbed area

== Permissions by workload
Each workload uses permissions to perform certain tasks in Workload Factory. Scroll to the workload you use to view the list of permissions, their purpose, where they are used, and which modes support them. 

=== Permissions for storage workloads

No input

=== Permissions for database workloads
The following table displays the permissions for database workloads. 

[cols=5*,options="header"]
|===

| Purpose
| Action
| Where used
| Read mode
| Automate mode

| Get metric statistics for FSx for ONTAP, EBS, and FSx for Windows File Server
| cloudwatch:GetMetricStatistics | Inventory (Detection) and Explore savings | Yes | No

| List and set triggers for events 
| sns:ListTopics | Deployment | Yes | No

.4+| Get details for EC2 instances 
| ec2:DescribeInstances | Inventory (Detection) and Explore savings | Yes | No
| ec2:DescribeKeyPairs | Deployment | Yes | No
| ec2:DescribeNetworkInterfaces | Deployment | Yes | No
| ec2:DescribeInstanceTypes | Deployment and Explore savings | Yes | No

.6+| Get details to fill in the FSx for ONTAP deployment form
| ec2:DescribeVpcs | Deployment and Inventory (Detection) | Yes | No
| ec2:DescribeSubnets | Deployment and Inventory (Detection) | Yes | No
| ec2:DescribeSecurityGroups | Deployment | Yes | No
| ec2:DescribeImages | Deployment | Yes | No
| ec2:DescribeRegions | Deployment | Yes | No
| ec2:DescribeRouteTables | Deployment and Inventory (Detection) | Yes | No

| Get any existing VPC endpoints to determine if new endpoints need to be created before deployments
| ec2:DescribeVpcEndpoints | Deployment and Inventory (Detection) | Yes | No

| Get instance types available in region for validation nodes (t2.micro/t3.micro) 
| ec2:DescribeInstanceTypeOfferings | Deployment | Yes | No

| Get snapshot details of each attached EBS volumes for pricing and savings estimate
| ec2:DescribeSnapshots | Explore savings | Yes | No

| Get details of each attached EBS volumes for pricing and savings estimate
| ec2:DescribeVolumes | Inventory (Detection) and Explore savings | Yes | No

.3+| Get KMS key details for FSx for ONTAP file system encryption
| kms:ListAliases | Deployment | Yes | No
| kms:ListAliases | Deployment | Yes | No
| kms:DescribeKey | Deployment | Yes | No

| Get list of CloudFormation stacks running in the environment to check quota limit
| cloudformation:ListStacks | Deployment | Yes | No

| Get list of AWS managed active directories in the region
| ds:DescribeDirectories | Deployment | Yes | No

.5+| Get volume, backup, SVM, file systems in AZ, and tags for FSx for ONTAP file system
| fsx:DescribeVolumes | Inventory(Detection) and Explore Savings | Yes | No
| fsx:DescribeBackups | Inventory(Detection) and Explore Savings | Yes | No
| fsx:DescribeStorageVirtualMachines | Deployment, Manage operations, and Inventory (Detection) | Yes | No
| fsx:DescribeFileSystems | Deployment, Manage operations, Inventory (Detection), and Explore savings | Yes | No
| fsx:ListTagsForResource | Manage operations | Yes | No

| Get service quota limits for CloudFormation and VPC
| servicequotas:ListServiceQuotas | Deployment | Yes | No

| Use SSM-based query to get the updated list of FSx for ONTAP supported regions
| ssm:GetParametersByPath | Deployment | Yes | No

| Poll for SSM response after sending command for manage operations post deployment
| ssm:GetCommandInvocation | Manage operations, Inventory (Detection), and Explore savings | Yes | No

| Send commands over SSM to EC2 instances 
| ssm:SendCommand | Manage operations, Inventory (Detection), and Explore savings | Yes | No

| To get the SSM connectivity status on instances post deployment
| ssm:GetConnectionStatus |  Manage operations and Inventory (Detection) | Yes | No

.4+| Get, list, create, and delete SSM parameters for AD, FSx for ONTAP, and SQL user credentials used during deployment or managed in your AWS account
| ssm:GetParameter | Deployment and manage operations | Yes | No
| ssm:GetParameters | Manage operations | Yes | No
| ssm:PutParameter | Deployment and manage operations | Yes | No
| ssm:DeleteParameters | Manage operations | Yes | No

.9+| Associate network resources to SQL nodes and validation nodes, and add additional secondary IPs to SQL nodes
| ec2:AllocateAddress | Deployment | Yes | Yes
| ec2:AllocateHosts | Deployment | Yes | Yes
| ec2:AssignPrivateIpAddresses | Deployment | Yes | Yes
| ec2:AssociateAddress | Deployment | Yes | Yes
| ec2:AssociateRouteTable | Deployment | Yes | Yes
| ec2:AssociateSubnetCidrBlock | Deployment | Yes | Yes
| ec2:AssociateVpcCidrBlock | Deployment | Yes | Yes
| ec2:AttachInternetGateway | Deployment | Yes | Yes
| ec2:AttachNetworkInterface | Deployment | Yes | Yes

... And the list goes on.

|===

=== Permissions for GenAI workloads

No input

=== Permissions for VMware workloads

No input

== Change log

As permissions are added and removed, we'll note them in the sections below.
//Example: 
//=== 9 May 2024

//The following permissions is now required for Cloud Volumes ONTAP:

//ec2:DescribeAvailabilityZones
