settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Setup and administration docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /reference-limitations.html
    - title: Get started
      entries:
        - title: Learn the basics
          entries: 
            - title: Workload Factory
              url: /concept-overview.html
            - title: Accounts
              url: /concept-netapp-accounts.html
            - title: Links
              url: /concept-links.html
        - title: Get started
          entries:
            - title: Getting started workflow
              url: /task-quick-start.html
            - title: Prepare networking for using the Workload Factory console
              url: /reference-networking-saas-console.html
            - title: Sign up to Workload Factory
              url: /task-sign-up-saas.html
            - title: What you can do next
              url: /reference-whats-next.html
        - title: Log in to Workload Factory
          url: /task-logging-in.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html          
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Workload Factory
  repo: workload-family