settings:
  name: Setup and administration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  release_notes_autogen:
    release_notes_repo: workload-relnotes
sidebar:
  entries:
    - title: Setup and administration docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn the basics
          entries: 
            - title: Learn about NetApp Workload Factory
              url: /workload-factory-overview.html
            - title: Console experiences
              url: /console-experiences.html  
            - title: Permissions 
              url: /permissions-reference.html  
        - title: Quick start
          url: /quick-start.html
        - title: Sign up to Workload Factory
          url: /sign-up-saas.html
        - title: Add AWS credentials
          url: /add-credentials.html
        - title: Optimize workloads with Workload Factory
          url: /whats-next.html
    - title: Administer Workload Factory
      entries:
        - title: Log in to Workload Factory
          url: /log-in.html
        - title: Manage service accounts
          url: /manage-service-accounts.html
        - title: Build and operate well-architected workloads
          url: /well-architected-workloads.html
        - title: Configure notifications
          url: /configure-notifications.html
        - title: Automate tasks using Codebox
          entries:
            - title: Learn about Codebox
              url: /codebox-automation.html
            - title: Use Codebox to generate code
              url: /use-codebox.html
        - title: Use CloudShell
          url: /use-cloudshell.html
        - title: Remove credentials
          url: /manage-credentials.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html          
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: NetApp Workload Factory
  repo: workload-family
  