settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Setup and administration docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /limitations.html
    - title: Get started
      entries:
        - title: Learn the basics
          entries: 
            - title: Workload Factory overview
              url: /workload-factory-overview.html
            - title: Operational modes
              url: /operational-modes.html
            - title: Accounts
              url: /workload-factory-accounts.html
            - title: Connectivity links
              url: /connectivity-links.html
            - title: Codebox automation
              url: /codebox-automation.html
        - title: Get started
          entries:
            - title: Getting started workflow
              url: /quick-start.html
            - title: Prepare networking for using the Workload Factory console
              url: /networking-saas-console.html
            - title: Sign up to Workload Factory
              url: /sign-up-saas.html
            - title: What you can do next
              url: /whats-next.html
        - title: Log in to Workload Factory
          url: /logging-in.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html          
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Workload Factory
  repo: workload-family