settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Setup and administration docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /limitations.html
    - title: Get started
      entries:
        - title: Learn the basics
          entries: 
            - title: Workload Factory overview
              url: /workload-factory-overview.html
            - title: Operational modes
              url: /operational-modes.html
        - title: Quick start
          url: /quick-start.html
        - title: Prepare your networking
          url: /networking-saas-console.html
        - title: Sign up to Workload Factory
          url: /sign-up-saas.html
        - title: Add AWS credentials
          url: /add-credentials.html
        - title: What you can do next
          url: /whats-next.html
    - title: Administer Workload Factory
      entries:
        - title: Log in to Workload Factory
          url: /log-in.html
        - title: Set up identity federation
          url: /federation.html
        - title: Manage your account
          entries:
            - title: Learn about accounts
              url: /workload-factory-accounts.html
            - title: Manage your account
              url: /manage-netapp-accounts.html
            - title: Create another account
              url: /create-another-account.html
        - title: Provide connectivity using links
          entries:
            - title: Learn about links
              url: /connectivity-links.html
            - title: Manage links
              url: /manage-links.html
        - title: Automate tasks using Codebox
          entries:
            - title: Learn about Codebox
              url: /codebox-automation.html
            - title: Use Codebox to generate code
              url: /using-codebox.html
        - title: Remove credentials
          url: /manage-credentials.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html          
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Workload Factory
  repo: workload-family