settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Setup and administration docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /limitations.html
    - title: Get started
      entries:
        - title: Learn the basics
          entries: 
            - title: Workload Factory overview
              url: /workload-factory-overview.html
            - title: Accounts
              url: /workload-factory-accounts.html
            - title: Credentials and permissions
              url: /credentials-overview.html
            - title: Operational modes
              url: /operational-modes.html
            - title: Connectivity links
              url: /connectivity-links.html
            - title: Codebox automation
              url: /codebox-automation.html
            - title: Storage calculators
              url: /storage-calculators.html
        - title: Get started
          entries:
            - title: Getting started workflow
              url: /quick-start.html
            - title: Prepare networking to use Workload Factory
              url: /networking-saas-console.html
            - title: Sign up to Workload Factory
              url: /sign-up-saas.html
            - title: Add AWS credentials
              url: /add-credentials.html
            - title: What you can do next
              url: /whats-next.html
        - title: Log in to Workload Factory
          url: /log-in.html
    - title: Administer Workload Factory
      entries:
        - title: Identity federation
          url: /federation.html
        - title: Workload Factory accounts
          entries:
            - title: Manage your Workload Factory account
              url: /manage-netapp-accounts.html
            - title: Create another Workload Factory account
              url: /create-another-account.html
        - title: Credentials and permissions
          entries:  
            - title: Manage credentials
              url: /manage-credentials.html
        - title: Links
          entries:
            - title: Manage links
              url: /manage-links.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html          
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Workload Factory
  repo: workload-family