=== Permissions update

In this release, we have made significant updates to permission policies for Storage, Database, and VMware workloads to enhance security and user control. You can customize your permission settings more granularly, adding or dismissing permissions as you see fit.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html[Permissions reference for Workload Factory]

=== New notification for Storage

The NetApp Workload Factory notification service includes the notification for automatic inode management for Storage. 

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html[Notifications for NetApp Workload Factory]

=== Threshold warnings for automatic capacity and inode management

Automatic capacity and inode management for Storage can be set up with a warning threshold that triggers a notification from the Workload Factory notification service. To use this feature, you must enable the Workload Factory notification service first.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html[Configure notifications for NetApp Workload Factory]